<?xml version="1.0"?>
<robot name="three_wheeled_car"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_diameter" value="0.072" />
    <xacro:property name="wheel_length" value="0.008" />
    <xacro:property name="wheel_radius" value="${wheel_diameter/2}" />
    <xacro:property name="base_height" value="${wheel_diameter/3}" />
    <xacro:property name="base_radius" value="0.175" />
    <xacro:property name="indicator_length" value="0.01" />
    <xacro:property name="indicator_depth" value="0.001" />
    <xacro:property name="head_length" value="0.03" />
    <xacro:property name="passive_wheel_radius" value="0.012" />

    <xacro:property name="base_mass" value="0.2" />
    <xacro:property name="head_mass" value="0.02" />
    <xacro:property name="wheel_mass" value="0.025" />
    <xacro:property name="passive_wheel_mass" value="0.01" />
    <xacro:property name="passive_wheel_holder_mass" value="0.015" />

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia ixx="${m*(3*r*r + h*h)/12}" ixy="0.0" ixz="0.0" iyy="${m*(3*r*r + h*h)/12}" iyz="0.0" izz="${m*r*r/2}" />
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r">
        <inertia ixx="${m*r*r*2/5}" ixy="0.0" ixz="0.0" iyy="${m*r*r*2/5}" iyz="0.0" izz="${m*r*r*2/5}" />
    </xacro:macro>

    <xacro:macro name="cube_inertia" params="m h">
        <inertia ixx="${m*h*h/6}" ixy="0.0" ixz="0.0" iyy="${m*h*h/6}" iyz="0.0" izz="${m*h*h/6}" />
    </xacro:macro>


    <link name="base_link">
        <visual>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
            <material name="red">
                <color rgba="0.8 0 0 0.5"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${base_mass}" />
            <origin rpy="0 0 0" />
            <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
        </inertial>
    </link>


    <link name="base_footprint">
    </link>
    <joint name="footprint_to_base" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel" params="wheel">
        <link name="${wheel}_wheel">
            <visual>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 0.5"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${wheel_mass}" />
                <origin rpy="0 0 0" />
                <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel wheel="right"/>
    <xacro:wheel wheel="left"/>

    <xacro:macro name="wheel_joint" params="wheel y">
        <joint name="base_to_${wheel}_wheel" type="continuous">
            <parent link="base_link" />
            <child link="${wheel}_wheel" />
            <origin xyz="0 ${y} 0" rpy="-1.57 0 0" />
            <axis xyz="0 0 1" />
        </joint>
    </xacro:macro>

    <xacro:wheel_joint wheel="right" y="${-(base_radius + wheel_length/2)}" />
    <xacro:wheel_joint wheel="left" y="${base_radius + wheel_length/2}" />

    <link name="head">
        <visual>
            <geometry>
                <box size="${head_length} ${head_length} ${head_length}"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 0.5"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${head_length} ${head_length} ${head_length}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${head_mass}" />
            <origin rpy="0 0 0" />
            <xacro:cube_inertia m="${head_mass}" h="${head_length}" />
        </inertial>
    </link>

    <joint name="base_to_head" type="fixed">
        <parent link="base_link"/>
        <child link="head"/>
        <origin xyz="${base_radius - head_length/2 - head_length/5} 0 ${(base_height + head_length)/2}" rpy="0 0 0"/>
    </joint>

    <link name="passive_wheel_holder">
        <visual>
            <geometry>
                <cylinder length="${base_height - passive_wheel_radius}" radius="${passive_wheel_radius}"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 0.5"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${base_height - passive_wheel_radius}" radius="${passive_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${passive_wheel_holder_mass}" />
            <origin rpy="0 0 0" />
            <xacro:cylinder_inertia m="${passive_wheel_holder_mass}" r="${passive_wheel_radius}" h="${base_height - passive_wheel_radius}" />
        </inertial>
    </link>

    <joint name="base_to_passive_wheel_holder" type="fixed">
        <parent link="base_link"/>
        <child link="passive_wheel_holder"/>
        <origin xyz="${base_radius - head_length/2 - head_length/5} 0 ${-(base_height - passive_wheel_radius/2)}" rpy="0 0 0"/>
    </joint>

    <link name="passive_wheel">
        <visual>
            <geometry>
                <sphere radius="${passive_wheel_radius}"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 0.5"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${passive_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${passive_wheel_mass}" />
            <origin rpy="0 0 0" />
            <xacro:sphere_inertia m="${passive_wheel_mass}" r="${passive_wheel_radius}" />
        </inertial>
    </link>

    <joint name="passive_wheel_holder_to_passive_wheel" type="fixed">
        <parent link="passive_wheel_holder"/>
        <child link="passive_wheel"/>
        <origin xyz="0 0 ${(-(base_height - passive_wheel_radius)/2)}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel_indicator" params="wheel number">
        <link name="${wheel}_wheel_indicator_${number}">
            <visual>
                <geometry>
                    <box size="${indicator_length} ${indicator_length} ${indicator_depth}"/>
                </geometry>
                <material name="cyan">
                    <color rgba="0 1 1 1" />
                </material>
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_indicator wheel="left" number="1" />
    <xacro:wheel_indicator wheel="left" number="2" />
    <xacro:wheel_indicator wheel="left" number="3" />
    <xacro:wheel_indicator wheel="right" number="1" />
    <xacro:wheel_indicator wheel="right" number="2" />
    <xacro:wheel_indicator wheel="right" number="3" />

    <xacro:macro name="wheel_indicator_joint" params="wheel number x y z yaw">
        <joint name="${wheel}_wheel_to_${wheel}_wheel_indicator_${number}" type="fixed">
            <parent link="${wheel}_wheel" />
            <child link="${wheel}_wheel_indicator_${number}" />
            <origin xyz="${x} ${y} ${z}" rpy="0 0 ${yaw}" />
        </joint>
    </xacro:macro>

    <xacro:wheel_indicator_joint wheel="left" number="1" x="0" y="${-(wheel_radius - indicator_length/2)}" z="${wheel_length/2 + indicator_depth/2}" yaw="0" />
    <xacro:wheel_indicator_joint wheel="left" number="2" x="${(wheel_radius - indicator_length/2)*sin(pi/3)}" y="${(wheel_radius - indicator_length/2)*cos(pi/3)}" z="${wheel_length/2 + indicator_depth/2}" yaw="${2*pi/3}" />
    <xacro:wheel_indicator_joint wheel="left" number="3" x="${(wheel_radius - indicator_length/2)*sin(-pi/3)}" y="${(wheel_radius - indicator_length/2)*cos(pi/3)}" z="${wheel_length/2 + indicator_depth/2}" yaw="${-2*pi/3}" />
    <xacro:wheel_indicator_joint wheel="right" number="1" x="0" y="${-(wheel_radius - indicator_length/2)}" z="${-(wheel_length/2 + indicator_depth/2)}" yaw="0" />
    <xacro:wheel_indicator_joint wheel="right" number="2" x="${(wheel_radius - indicator_length/2)*sin(pi/3)}" y="${(wheel_radius - indicator_length/2)*cos(pi/3)}" z="${-(wheel_length/2 + indicator_depth/2)}" yaw="${2*pi/3}" />
    <xacro:wheel_indicator_joint wheel="right" number="3" x="${(wheel_radius - indicator_length/2)*sin(-pi/3)}" y="${(wheel_radius - indicator_length/2)*cos(pi/3)}" z="${-(wheel_length/2 + indicator_depth/2)}" yaw="${-2*pi/3}" />

</robot>